# Generated by Django 4.1.7 on 2023-02-20 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_book_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='task',
            new_name='book',
        ),
    ]
